apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-app-deployment
  labels:
    app: hello-app
spec:
  replicas: 2 # Run 2 instances of the application
  selector:
    matchLabels:
      app: hello-app
  template:
    metadata:
      labels:
        app: hello-app
    spec:
      containers:
      - name: hello-app-container
        # Jenkins will replace this tag with the actual image:tag after build
        image: 1411ayush/hello-app:latest 
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: hello-app-service
spec:
  # NodePort exposes the service on a port accessible from outside the cluster
  type: NodePort 
  selector:
    app: hello-app
  ports:
  - port: 80
    targetPort: 80
    # Use a high port number (e.g., 30000-32767) for local testing
    nodePort: 30080
